//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktura
    {
        public Faktura()
        {
            this.Faktura_operacja = new HashSet<Faktura_operacja>();
        }
    
        public int Id_faktura { get; set; }
        public Nullable<int> Id_hurtownia { get; set; }
        public string Numer { get; set; }
    
        public virtual ICollection<Faktura_operacja> Faktura_operacja { get; set; }
        public virtual Hurtownia Hurtownia { get; set; }
    }
}
