//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktura_operacja
    {
        public int ID_faktura { get; set; }
        public int ID_operacja { get; set; }
        public int ID_faktura_operacja { get; set; }
    
        public virtual Faktura Faktura { get; set; }
        public virtual Operacja Operacja { get; set; }
    }
}
