//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Web.Script.Serialization;
    
    public partial class Hurtownia
    {
        public Hurtownia()
        {
            this.Faktura = new HashSet<Faktura>();
        }
    
        public int Id_hurtownia { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> NIP { get; set; }

        [JsonIgnore] 
        [ScriptIgnore]
        public virtual ICollection<Faktura> Faktura { get; set; }
    }
}
