//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lek
    {
        public Lek()
        {
            this.Operacjas = new HashSet<Operacja>();
        }
    
        public int Id_lek { get; set; }
        public string Nazwa { get; set; }
        public string Postac { get; set; }
        public Nullable<int> Opakowanie { get; set; }
        public string Dawka { get; set; }
    
        public virtual ICollection<Operacja> Operacjas { get; set; }
    }
}
