//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lista_hurtowni
    {
        public int ID_hurtownia { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> NIP { get; set; }
    }
}
