//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacja
    {
        public Operacja()
        {
            this.Faktura = new HashSet<Faktura>();
        }
    
        public int Id_operacja { get; set; }
        public int Id_lek { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Id_user { get; set; }
        public Nullable<int> Przychod { get; set; }
        public Nullable<int> Rozchod { get; set; }
        public Nullable<double> Netto { get; set; }
        public Nullable<double> Brutto { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Lek Lek { get; set; }
        public virtual ICollection<Faktura> Faktura { get; set; }
    }
}
