//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprawdz_faktury
    {
        public int Id_faktura { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Numer { get; set; }
        public string Nazwa { get; set; }
        public Nullable<double> Netto { get; set; }
        public Nullable<double> Brutto { get; set; }
    }
}
